from manim import BLACK, BLUE_A, BLUE_B, BLUE, BLUE_D, BLUE_E, DARK_BLUE, DARK_GREY, GREEN_A, GREEN_B,\
    GREEN, GREEN_D, GREEN_E, GREY, LIGHT_GREY, MAROON_A, MAROON_B, RED, RED_D, TEAL, WHITE, YELLOW
